#!/bin/bash
sudo apt-get -y update 

sudo apt-get -y install nginx

sudo apt-get upgrade nginx

sudo systemctl start nginx

sudo mkdir -p /var/www/dks.com/html

sudo chown -R $USER:$USER /var/www/dks.com/html

sudo chmod -R 755 /var/www


echo "<head>
        <title>powerup cloud.com !</title>
    </head>
    <body>
        <h1>welcome to powerupcloud technologies!</h1>
    </body>
</html>" > /var/www/dks.com/html/index.html

my_ip=$(curl ipconfig.in/ip)
echo "$my_ip"

echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/dks.com/html;
        index index.html index.htm index.nginx-debian.html;

        server_name $my_ip;
        server_name " >> /etc/nginx/sites-available/dks.com

perl -p -i -e "s/\r//g" /etc/nginx/sites-available/dks.com


cat << 'EOF' >>/etc/nginx/sites-available/dks.com
location / {
                try_files $uri $uri/ =404;
        }
}
EOF


sudo ln -s /etc/nginx/sites-available/dks.com /etc/nginx/sites-enabled/

sudo nginx -t

sudo systemctl restart nginx
